fixtures:
  symlinks:
    vitess: "#{source_dir}"
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib
      ref: 4.3.2
    vcsrepo:
      repo: git://github.com/puppetlabs/puppetlabs-vcsrepo
      ref: 1.2.0
